# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/C/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "/C/Program Files/CMake/bin/cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /C/work/Clang/vscode_proj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /C/work/Clang/vscode_proj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/C/Program Files/CMake/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/C/Program Files/CMake/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /C/work/Clang/vscode_proj/CMakeFiles /C/work/Clang/vscode_proj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /C/work/Clang/vscode_proj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vscode_proj

# Build rule for target.
vscode_proj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vscode_proj
.PHONY : vscode_proj

# fast build rule for target.
vscode_proj/fast:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/build
.PHONY : vscode_proj/fast

fizz_buzz.obj: fizz_buzz.cpp.obj

.PHONY : fizz_buzz.obj

# target to build an object file
fizz_buzz.cpp.obj:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/fizz_buzz.cpp.obj
.PHONY : fizz_buzz.cpp.obj

fizz_buzz.i: fizz_buzz.cpp.i

.PHONY : fizz_buzz.i

# target to preprocess a source file
fizz_buzz.cpp.i:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/fizz_buzz.cpp.i
.PHONY : fizz_buzz.cpp.i

fizz_buzz.s: fizz_buzz.cpp.s

.PHONY : fizz_buzz.s

# target to generate assembly for a file
fizz_buzz.cpp.s:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/fizz_buzz.cpp.s
.PHONY : fizz_buzz.cpp.s

hello_world.obj: hello_world.cpp.obj

.PHONY : hello_world.obj

# target to build an object file
hello_world.cpp.obj:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/hello_world.cpp.obj
.PHONY : hello_world.cpp.obj

hello_world.i: hello_world.cpp.i

.PHONY : hello_world.i

# target to preprocess a source file
hello_world.cpp.i:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/hello_world.cpp.i
.PHONY : hello_world.cpp.i

hello_world.s: hello_world.cpp.s

.PHONY : hello_world.s

# target to generate assembly for a file
hello_world.cpp.s:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/hello_world.cpp.s
.PHONY : hello_world.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/vscode_proj.dir/build.make CMakeFiles/vscode_proj.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... vscode_proj"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fizz_buzz.obj"
	@echo "... fizz_buzz.i"
	@echo "... fizz_buzz.s"
	@echo "... hello_world.obj"
	@echo "... hello_world.i"
	@echo "... hello_world.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

